# Import the argument parser module for handling command-line options
import argparse
# Import random to shuffle target error rows deterministically
import random
# Import pandas to create and export the spreadsheet structure
import pandas as pd


def generate_corrupt_hanoi_sheet(num_disks: int, filename: str):
    """
    Generates a Hanoi test spreadsheet containing every error condition
    checked by verify_hanoi.py across an optimal 2^n - 1 move sequence.
    """
    # Fix the random seed to produce reproducible row selections
    random.seed(42)

    # Compute optimal move count using the recurrence relation limit 2^n - 1
    total_moves = (2**num_disks) - 1

    # Verify that the sequence has enough moves to test all 8 scenarios
    if total_moves < 8:
        raise ValueError(
            f"Disk count {num_disks} produces {total_moves} moves. "
            "A minimum of 4 disks (15 moves) is required to test all 8 error cases."
        )

    # Initialize a list to hold optimal legal moves
    base_moves = []

    # Define recursive solver to compute optimal sequence
    def solve_hanoi(n, source, target, aux):
        # Base condition: single disk move
        if n == 1:
            base_moves.append((1, source, target))
            return
        # Move n-1 disks to the auxiliary peg
        solve_hanoi(n - 1, source, aux, target)
        # Move the nth disk to the target peg
        base_moves.append((n, source, target))
        # Move n-1 disks from auxiliary to target peg
        solve_hanoi(n - 1, aux, target, source)

    # Solve puzzle starting at Peg 1, targeting Peg 3, using Peg 2
    solve_hanoi(num_disks, 1, 3, 2)

    # Choose 8 distinct row indices between index 1 and total_moves - 1
    # Index 0 is reserved as a clean legal baseline
    available_indices = list(range(1, total_moves))
    random.shuffle(available_indices)

    # Map each error type to a unique row index
    error_mapping = {
        "Malformed Data": available_indices.pop(),
        "Invalid Peg ID": available_indices.pop(),
        "Empty Source Peg": available_indices.pop(),
        "Ghost Disk": available_indices.pop(),
        "Size Inversion": available_indices.pop(),
        "Identical Pegs": available_indices.pop(),
        "Visual Drift": available_indices.pop(),
        "Human Discrepancy": available_indices.pop(),
    }

    # Invert mapping to look up planned error by row index during iteration
    index_to_error = {v: k for k, v in error_mapping.items()}

    # Initialize ground-truth peg dictionary with disks sorted on Peg 1
    pegs = {1: list(range(1, num_disks + 1)), 2: [], 3: []}

    # Initialize container to hold output row dictionaries
    rows = []

    # Iterate through each step generated by the solver
    for idx, (d, src, dst) in enumerate(base_moves):
        # Human-readable move number (1-indexed)
        move_num = idx + 1
        # Retrieve planned error for the current index
        error = index_to_error.get(idx, "None")
        # Default human audit label
        human_val = "Legal"

        # ----------------------------------------------------
        # Execution and Corruption Logic
        # ----------------------------------------------------
        if error == "None":
            # Execute standard move on simulation board
            disk_val = pegs[src].pop(0)
            pegs[dst].insert(0, disk_val)

        elif error == "Malformed Data":
            # Inject a non-numeric string into the From column
            src = "one"
            human_val = "Illegal"

        elif error == "Invalid Peg ID":
            # Assign an out-of-bounds destination peg identifier
            dst = 4
            human_val = "Illegal"

        elif error == "Empty Source Peg":
            # Identify pegs that currently have zero disks
            empty_pegs = [p for p in pegs if len(pegs[p]) == 0]
            if empty_pegs:
                src = empty_pegs[0]
            else:
                # Force Peg 2 to be empty if all pegs are occupied
                src = 2
                pegs[src] = []
            # Choose a destination different from the empty source
            dst = 1 if src != 1 else 3
            d = 1
            human_val = "Illegal"

        elif error == "Ghost Disk":
            # Identify pegs with disks to find an active peg
            occupied = [p for p in pegs if len(pegs[p]) > 0]
            src = occupied[0]
            actual_top = pegs[src][0]
            # Select a disk number that differs from the top disk
            d = actual_top + 1 if actual_top + 1 <= num_disks else actual_top - 1
            if d == 0:
                d = 99
            # Route to an alternate peg
            dst = 1 if src != 1 else 2
            human_val = "Illegal"

        elif error == "Size Inversion":
            # Select a destination peg that already contains a disk
            occupied = [p for p in pegs if len(pegs[p]) > 0]
            dst = occupied[0]
            target_top = pegs[dst][0]
            # Select a source peg distinct from destination
            available_sources = [p for p in pegs if p != dst]
            src = available_sources[0]
            # Set the moving disk larger than the target top disk
            d = target_top + 1
            # Add this larger disk to the source peg to satisfy top-disk check
            pegs[src] = [d] + pegs[src]
            human_val = "Illegal"

        elif error == "Identical Pegs":
            # Identify a non-empty peg to ensure Gate 3 (Empty Peg) does not trigger
            occupied = [p for p in pegs if len(pegs[p]) > 0]
            src = occupied[0]
            dst = src
            d = pegs[src][0]
            human_val = "Illegal"

        elif error == "Visual Drift":
            # Execute valid physical move, then inject visual corruption later
            disk_val = pegs[src].pop(0)
            pegs[dst].insert(0, disk_val)
            human_val = "Legal"

        elif error == "Human Discrepancy":
            # Introduce an illegal peg move while human marks it as Legal
            dst = 5
            human_val = "Legal"

        # Record visual state as string representations of lists
        p1_str = str(pegs[1])
        p2_str = str(pegs[2])
        p3_str = str(pegs[3])

        # Overwrite visual representation if Visual Drift is targeted
        if error == "Visual Drift":
            p3_str = "[99]"

        # Append row dictionary to row collection
        rows.append({
            "Move #": move_num,
            "Disk": d,
            "From": src,
            "To": dst,
            "Peg 1": p1_str,
            "Peg 2": p2_str,
            "Peg 3": p3_str,
            "Human Check": human_val,
            "Targeted Error": error,
        })

    # Convert row dictionaries into a pandas DataFrame
    df = pd.DataFrame(rows)

    # Save DataFrame to Excel file without index column
    df.to_excel(filename, index=False)

    # Print summary of generated test suite
    print(f"Generated test file: {filename}")
    print(f"Total Rows: {total_moves} (for {num_disks} disks)")
    print("Injected Error Mapping:")
    for err, r_idx in sorted(error_mapping.items(), key=lambda item: item[1]):
        print(f"  - Row {r_idx + 1}: {err}")


# Define entry point for execution via command-line arguments
if __name__ == "__main__":
    # Create argument parser
    parser = argparse.ArgumentParser(
        description="Generate negative testing spreadsheet for verify_hanoi.py."
    )
    # Define disk argument (-n / --disks)
    parser.add_argument(
        "-n",
        "--disks",
        type=int,
        default=4,
        help="Number of disks (minimum: 4, default: 4)",
    )
    # Define output file argument (-o / --output)
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default="test_corrupt_hanoi.xlsx",
        help="Output filename (default: test_corrupt_hanoi.xlsx)",
    )

    # Parse arguments from command line
    args = parser.parse_args()

    # Call generator function
    generate_corrupt_hanoi_sheet(num_disks=args.disks, filename=args.output)
    